// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Gn5ioDzCctXC-MCPjACTw0lJxz9ESQI',
    appId: '1:265871202894:web:797a1974d023b4639c811f',
    messagingSenderId: '265871202894',
    projectId: 'failedtoconnect-4a160',
    authDomain: 'failedtoconnect-4a160.firebaseapp.com',
    storageBucket: 'failedtoconnect-4a160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhlI0xZsbznBuiSLVylzOkNaNIVjTjwo',
    appId: '1:265871202894:android:e5ec8de2fdd3f5209c811f',
    messagingSenderId: '265871202894',
    projectId: 'failedtoconnect-4a160',
    storageBucket: 'failedtoconnect-4a160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnv91N6kSn-g52d4CfjjXdtJHVN2ZduxM',
    appId: '1:265871202894:ios:13f119e8500025c39c811f',
    messagingSenderId: '265871202894',
    projectId: 'failedtoconnect-4a160',
    storageBucket: 'failedtoconnect-4a160.appspot.com',
    iosBundleId: 'com.trytryagain.failedtoconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnv91N6kSn-g52d4CfjjXdtJHVN2ZduxM',
    appId: '1:265871202894:ios:13f119e8500025c39c811f',
    messagingSenderId: '265871202894',
    projectId: 'failedtoconnect-4a160',
    storageBucket: 'failedtoconnect-4a160.appspot.com',
    iosBundleId: 'com.trytryagain.failedtoconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Gn5ioDzCctXC-MCPjACTw0lJxz9ESQI',
    appId: '1:265871202894:web:8897c47603bd70b59c811f',
    messagingSenderId: '265871202894',
    projectId: 'failedtoconnect-4a160',
    authDomain: 'failedtoconnect-4a160.firebaseapp.com',
    storageBucket: 'failedtoconnect-4a160.appspot.com',
  );

}